version: 2
project_name: nano-agent

builds:
  - id: nano-agent
    main: ./cmd/nano-agent
    binary: nano-agent
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X github.com/rkirkendall/nano-agent/internal/version.Version={{.Version}}

archives:
  - id: default
    builds: [nano-agent]
    format_overrides:
      - goos: windows
        format: zip
    format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    wrap_in_directory: true

# Homebrew tap config removed for now; can be re-added later with v2 schema fields

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'


